# -*- coding: utf-8 -*-
"""Algoritmo DES Base64.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ncKOj_s6Aw55sClAA55R173Yef2fHO6c
"""

import base64

key = base64.b64decode('c3Bpcml0dXM=')  #'spiritus'

encoded_text = """upa4z5/RUfCx1HVLFKLXOlIYSKb8a7zGn4D+d
lPRATPbnz4N4CCBdKWr978T35iXCktj86og7M
+2Qv260qHwkhbpxM1lXXNFcT/v7cb3UFy/5Q
9md49vA7I0o8XCsZyo7KOTgmRonpzXbHzwX
VOimcfTnh2v9pdggxCumDQ5jVpGrF8S7agqo
+Ogts7I+xWHVtOqtlvtgkwXdypikfDuzZV9/NaQ
CmChulm1No/GnZtPnxYsu5hZcPJN8MRUOUs
s+C9q+oIZGxf04cBbSZnt9RCPFkZcjxRcHLyVn
2TfsR7OJ0sbc4z19MqUxQvXPmb8CsRdgbs6
QQ6fxtJWBvkm6Bu3Leuuu1cNOqHmtjdamc5
xUtpzi7Z4UVWNgk67FIuzQGDcTfThFNumpjIiS
6A7jfQmxT+Y7cQqc4FyIz8+He4hQxCciwCu2X
LtNOFk+GXpM7BKZ5g4rInvOoR24xfLsZ8FVU
CCDOJkWBZJq+LNKuP1p5cq3OXJfGDOTAjT7
a/5pJXSarWTGuLMhrVDXLDLHc/QjOvphAqLb
g1kjbgY76WFZug9iktesLlpdBqpb/+8n8mrkXq
CYy0cZcGlbLMOqgOhcsKSkDzRo08J4dqpQjy
KCQroTltDbw=="""

encoded_text = encoded_text.replace("\n", "")

cipher_text = base64.b64decode(encoded_text)

iv = b'\x00' * 8

pip install pycryptodome

from Crypto.Cipher import DES
from Crypto.Util.Padding import unpad

des_cbc = DES.new(key, DES.MODE_CBC, iv)

try:
    decrypted_text = des_cbc.decrypt(cipher_text)
    decrypted_text = unpad(decrypted_text, 8).decode('utf-8', errors='ignore')
    print(decrypted_text)
except Exception as e:
    decrypted_text = str(e)